In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
%load_ext autoreload
%autoreload 2

from utils import load_trackmate_spots
from utils import load_trackmate_tracks
from utils import load_meanint_ROIs
from utils import remove_shorttracks_3
from utils import remove_shorttracks_spotsfile
from utils import split_table_by_track
from utils import first_10_frames
from utils import meanint_tracks_ch2

import sys
sys.path.append("..")

pd.set_option('display.max_columns', None) # Displays all columns of df

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
# Loads spots file and removes first three rows

D14_allROIs_spots_paths = ['/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/Tables/100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos14_1_w1conf561-488dual_ROI-1_merged_spots.csv',
                           '/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/Tables/100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos14_1_w1conf561-488dual_ROI-2_merged_spots.csv',
                           '/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/Tables/100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos14_1_w1conf561-488dual_ROI-3_merged_spots.csv',
                           '/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/Tables/100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos19_1_w1conf561-488dual_ROI-1_merged_spots.csv',
                           '/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/Tables/100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos19_1_w1conf561-488dual_ROI-2_merged_spots.csv',
                           '/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/Tables/100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos19_1_w1conf561-488dual_ROI-3_merged_spots.csv']

D14_allROIs_spots = []

for path in D14_allROIs_spots_paths:
    df = load_trackmate_spots(path)
    D14_allROIs_spots.append(df)

D14_allROIs_spots[0].head()

,LABEL,ID,TRACK_ID,QUALITY,POSITION_X,POSITION_Y,POSITION_Z,POSITION_T,FRAME,RADIUS,VISIBILITY,MANUAL_INTEGER_SPOT_FEATURE,MANUAL_DOUBLE_SPOT_FEATURE,HAS_MAX_QUALITY_IN_FRAME,MANUAL_SPOT_COLOR,MEAN_INTENSITY_CH1,MEDIAN_INTENSITY_CH1,MIN_INTENSITY_CH1,MAX_INTENSITY_CH1,TOTAL_INTENSITY_CH1,STD_INTENSITY_CH1,MEAN_INTENSITY_CH2,MEDIAN_INTENSITY_CH2,MIN_INTENSITY_CH2,MAX_INTENSITY_CH2,TOTAL_INTENSITY_CH2,STD_INTENSITY_CH2,CONTRAST_CH1,SNR_CH1,CONTRAST_CH2,SNR_CH2
0,ID145474,145474,0,2377.77099609375,69.52926717,109.33712612999999,0.0,0.5,10,0.20172901499999998,1,NaN,NaN,0,NaN,8864.42857142857,8774.0,7566.0,10550.0,186153.0,781.6220040037621,9174.047619047618,8942.0,6681.0,11706.0,192655.0,1347.8035641810152,0.04677295894160387,1.013505975229374,0.06420338379168884,0.8212921419770106
1,ID145731,145731,0,3834.151611328125,69.39478116,109.74058416,0.0,1.3,26,0.20172901499999998,1,NaN,NaN,0,NaN,9000.619047619048,8542.0,7538.0,11747.0,189013.0,1204.3610951948954,8420.333333333334,7975.0,5686.0,14483.0,176827.0,2029.4421975836942,0.07308238747248288,1.0179473543005784,0.06437491817512855,0.5018855034453941
2,ID145670,145670,0,3191.315185546875,68.99132313,109.74058416,0.0,0.8500000000000001,17,0.20172901499999998,1,NaN,NaN,1,NaN,9038.238095238095,8761.0,7987.0,11350.0,189803.0,964.2102936995593,9087.095238095239,8625.0,5697.0,12683.0,190829.0,1707.996513601884,0.058918126921717065,1.0431062768110229,0.08034633198758759,0.7913546319427699
3,ID145863,145863,0,4912.9501953125,68.99132313,110.00955617999999,0.0,1.6,32,0.20172901499999998,1,NaN,NaN,0,NaN,8888.190476190477,8414.0,6788.0,12443.0,186652.0,1694.301968925481,8579.333333333334,8118.0,5956.0,13574.0,180166.0,2161.4972202927615,0.09137340401505928,0.8784134388933585,0.09280098261469531,0.674124876932153
4,ID145796,145796,0,1968.628173828125,69.26029514999999,109.74058416,0.0,1.4500000000000002,29,0.20172901499999998,1,NaN,NaN,0,NaN,8098.571428571428,8038.0,6963.0,9539.0,170070.0,736.1725050168997,8198.619047619048,8304.0,5542.0,11667.0,172171.0,1693.500265018889,0.0420093926053911,0.8870203594265038,0.06279297123663859,0.572068182721432

In [3]:
# Loads track file and removes first three rows

D14_allROIs_tracks_paths = ['/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/Tables/100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos14_1_w1conf561-488dual_ROI-1_merged_tracks.csv',
                            '/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/Tables/100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos14_1_w1conf561-488dual_ROI-2_merged_tracks.csv',
                            '/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/Tables/100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos14_1_w1conf561-488dual_ROI-3_merged_tracks.csv',
                            '/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/Tables/100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos19_1_w1conf561-488dual_ROI-1_merged_tracks.csv',
                            '/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/Tables/100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos19_1_w1conf561-488dual_ROI-2_merged_tracks.csv',
                            '/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/Tables/100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos19_1_w1conf561-488dual_ROI-3_merged_tracks.csv']

D14_allROIs_tracks = []

for path in D14_allROIs_tracks_paths:
    df = load_trackmate_tracks(path)
    D14_allROIs_tracks.append(df)
    
D14_allROIs_tracks[4].head()

,LABEL,TRACK_INDEX,TRACK_ID,MANUAL_INTEGER_TRACK_FEATURE,MANUAL_DOUBLE_TRACK_FEATURE,NUMBER_SPOTS,NUMBER_GAPS,NUMBER_SPLITS,NUMBER_MERGES,NUMBER_COMPLEX,LONGEST_GAP,TRACK_DURATION,TRACK_START,TRACK_STOP,TRACK_DISPLACEMENT,TRACK_X_LOCATION,TRACK_Y_LOCATION,TRACK_Z_LOCATION,TRACK_MEAN_SPEED,TRACK_MAX_SPEED,TRACK_MIN_SPEED,TRACK_MEDIAN_SPEED,TRACK_STD_SPEED,TRACK_MEAN_QUALITY,TOTAL_DISTANCE_TRAVELED,MAX_DISTANCE_TRAVELED,CONFINEMENT_RATIO,MEAN_STRAIGHT_LINE_SPEED,LINEARITY_OF_FORWARD_PROGRESSION,MEAN_DIRECTIONAL_CHANGE_RATE
0,Track_348,0,0,NaN,NaN,8,0,0,0,0,0,0.35000000000000003,0.35000000000000003,0.7000000000000001,0.13448600999999627,125.18966455874998,37.588839795,0.0,3.1646740582363537,6.014397207654349,0.0,2.689720200000068,1.9976485569132845,6136.753479003906,1.1076359203827237,0.3007198603827177,0.12141716201613166,0.38424574285713214,0.12141716201613163,31.415926535897935
1,Track_349,1,1,NaN,NaN,46,5,0,0,0,3,2.7500000000000004,0.4,3.1500000000000004,0.6014397207654354,128.8259031443478,33.37007213347827,0.0,3.366612900101604,8.505642100563561,0.0,3.8038387858286646,2.3178436141483854,5801.823568592901,8.706107978227054,1.344860100000011,0.06908250187909051,0.21870535300561283,0.06496302351809213,16.498271692382254
2,Track_350,2,2,NaN,NaN,3,0,0,0,0,0,0.09999999999999998,0.7000000000000001,0.8,0.4252821050281784,126.64099275,36.66985206,0.0,4.591639592914453,5.379440400000142,3.8038387858287646,5.379440400000142,1.1141185858290512,3944.7012532552085,0.45916395929144516,0.4252821050281784,0.9262096826685805,4.252821050281785,0.9262096826685803,15.707963267950008
3,Track_351,3,3,NaN,NaN,4,0,0,0,0,0,0.15000000000000002,0.8,0.9500000000000001,0.6724300499999899,128.4005180475,33.4533949875,0.0,4.9061715384360784,6.014397207654489,2.689720199999781,6.014397207653967,1.9195031653378543,2631.211883544922,0.7359257307654118,0.6724300499999899,0.9137199881577966,4.482866999999932,0.9137199881577965,17.506498265872267
4,Track_352,4,4,NaN,NaN,4,0,0,0,0,0,0.15000000000000002,0.9500000000000001,1.1,0.0,130.04797166999998,30.999025304999996,0.0,1.793146799999998,2.6897202,0.0,2.6897201999999942,1.5529106815147724,2076.3753051757812,0.26897201999999965,0.13448600999999982,0.0,0.0,0.0,0.0

In [4]:
# Loads mean intensites of each ROI per image

D14_allROIs_meanint_paths = ['/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/ROIs/Meanint_ROIs_pos14.csv',
                             '/Volumes/gchao/bamfaile/Analysis/ACTB-KI/Batch20220930/D14/Slide1/ROIs/Meanint_ROIs_pos19.csv']

D14_allROIs_meanint = []

for path in D14_allROIs_meanint_paths:
    df = load_meanint_ROIs(path)
    D14_allROIs_meanint.append(df)
    
D14_allROIs_meanint[1].head()

                                                  Label      Mean    StdDev
0  1  100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos...  5933.697  1414.005
1  2  100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos...  6004.464  1340.178
2  3  100tp-561-100-50ms-1000g_488-10-50ms-1000g_pos...  5190.802  1483.487

In [5]:
# Removes tracks that are <= 3 from tracks file

D14_allROIs_tracks_filtered = []

for df in D14_allROIs_tracks:
    df = remove_shorttracks_3(df)
    D14_allROIs_tracks_filtered.append(df)

#pd.set_option('display.max_rows', None) # Displays all rows of df    
D14_allROIs_tracks_filtered[5].head()

,LABEL,TRACK_INDEX,TRACK_ID,MANUAL_INTEGER_TRACK_FEATURE,MANUAL_DOUBLE_TRACK_FEATURE,NUMBER_SPOTS,NUMBER_GAPS,NUMBER_SPLITS,NUMBER_MERGES,NUMBER_COMPLEX,LONGEST_GAP,TRACK_DURATION,TRACK_START,TRACK_STOP,TRACK_DISPLACEMENT,TRACK_X_LOCATION,TRACK_Y_LOCATION,TRACK_Z_LOCATION,TRACK_MEAN_SPEED,TRACK_MAX_SPEED,TRACK_MIN_SPEED,TRACK_MEDIAN_SPEED,TRACK_STD_SPEED,TRACK_MEAN_QUALITY,TOTAL_DISTANCE_TRAVELED,MAX_DISTANCE_TRAVELED,CONFINEMENT_RATIO,MEAN_STRAIGHT_LINE_SPEED,LINEARITY_OF_FORWARD_PROGRESSION,MEAN_DIRECTIONAL_CHANGE_RATE
0,Track_486,0,0,NaN,NaN,7,1,0,0,0,1,0.35000000000000003,0.0,0.35000000000000003,0.601439720765429,119.26987858285712,49.529276254285705,0.0,4.517156997732041,8.50564210056347,1.3448601000000338,5.379440399999852,2.5022747441341826,6113.787632533482,1.422390104319614,0.601439720765429,0.4228373910497089,1.7183992021869396,0.38041608982147573,24.565153010301515
1,Track_487,1,1,NaN,NaN,4,0,0,0,0,0,0.15000000000000002,0.0,0.15000000000000002,0.4252821050281784,110.480257215,61.4937280725,0.0,2.901372469218093,6.014397207654354,0.0,2.6897201999999254,3.0127796061376646,7206.2659912109375,0.43520587038271397,0.4252821050281784,0.9771975379242731,2.835214033521189,0.977197537924273,4.636476090008166
2,Track_489,3,3,NaN,NaN,13,1,0,0,0,1,0.65,0.0,0.65,0.19019193929144343,117.24076548692307,50.63915530384615,0.0,5.041841490402689,9.69792409775118,0.0,5.379440400000136,3.070573180799992,7042.878878079928,3.2377459467557026,1.0242149380729517,0.058742082429914,0.29260298352529757,0.05803494300292403,13.69116189377611
3,Track_490,4,4,NaN,NaN,5,0,0,0,0,0,0.2,0.0,0.2,0.0,109.848172968,62.53599465,0.0,1.3448600999998916,2.6897201999997833,0.0,2.6897201999997833,1.552910681514649,7012.6529296875,0.26897201999997833,0.13448600999998916,0.0,0.0,0.0,20.943951023931955
4,Track_494,8,8,NaN,NaN,21,1,0,0,0,3,1.1500000000000001,0.0,1.1500000000000001,1.9992782702125693,109.53565309714284,62.010858801428576,0.0,4.125370808780836,9.697924097751384,0.0,3.8038387858288694,2.6326254807748337,11230.559721447173,4.327099823780836,2.348697192092808,0.4620365491050042,1.7385028436631036,0.4214173523414445,13.997175043696119

In [20]:
# Creates trackIDs object 

D14_allROIs_trackIDs = []

for df in D14_allROIs_tracks_filtered:
    ID = df["TRACK_ID"].unique()
    D14_allROIs_trackIDs.append(ID)

D14_allROIs_trackIDs[1]

array(['0', '1', '2', '3', '5', '6', '7', '8', '9', '10', '11', '12',
       '14', '15', '16', '20', '23', '24', '25', '26', '27', '28', '33',
       '34', '35', '36', '38', '39', '40', '43', '45', '48', '49', '50',
       '51', '53', '54', '56', '57', '58', '59', '60'], dtype=object)

In [43]:
# Removes spots from spots file from tracks <= 3 in length

D14_allROIs_spots_filtered = []


for df, i in zip(D14_allROIs_spots, D14_allROIs_trackIDs):
    
    df = remove_shorttracks_spotsfile(df, i)
    D14_allROIs_spots_filtered.append(df)


#pd.set_option('display.max_rows', None) # Displays all rows of df  
D14_allROIs_spots_filtered[4].head(10)

,LABEL,ID,TRACK_ID,QUALITY,POSITION_X,POSITION_Y,POSITION_Z,POSITION_T,FRAME,RADIUS,VISIBILITY,MANUAL_INTEGER_SPOT_FEATURE,MANUAL_DOUBLE_SPOT_FEATURE,HAS_MAX_QUALITY_IN_FRAME,MANUAL_SPOT_COLOR,MEAN_INTENSITY_CH1,MEDIAN_INTENSITY_CH1,MIN_INTENSITY_CH1,MAX_INTENSITY_CH1,TOTAL_INTENSITY_CH1,STD_INTENSITY_CH1,MEAN_INTENSITY_CH2,MEDIAN_INTENSITY_CH2,MIN_INTENSITY_CH2,MAX_INTENSITY_CH2,TOTAL_INTENSITY_CH2,STD_INTENSITY_CH2,CONTRAST_CH1,SNR_CH1,CONTRAST_CH2,SNR_CH2
0,ID93328,93328,0,6514.07470703125,125.20647530999999,37.790568809999996,0.0,0.45,9,0.20172901499999998,1,NaN,NaN,1,NaN,8314.47619047619,7377.0,6302.0,13218.0,174604.0,1945.301869095067,8154.428571428572,7852.0,4935.0,14106.0,171243.0,2120.399622038935,0.12736385464377237,0.9657394524473941,0.10806233226728526,0.7500944555303242
1,ID93315,93315,0,6076.1396484375,125.20647530999999,37.6560828,0.0,0.4,8,0.20172901499999998,1,NaN,NaN,1,NaN,8216.190476190477,7783.0,5471.0,12593.0,172540.0,2175.239449326157,8262.57142857143,7325.0,5435.0,12763.0,173514.0,2154.32018445329,0.1248002516360828,0.8381726393574688,0.11321921351153034,0.7801433526721028
2,ID93304,93304,0,6424.98095703125,125.07198929999998,37.790568809999996,0.0,0.5,10,0.20172901499999998,1,NaN,NaN,1,NaN,8266.47619047619,7857.0,5724.0,12898.0,173596.0,2427.7421324977577,7991.0,7966.0,4135.0,12747.0,167811.0,2522.9776059251894,0.13772266715602108,0.8243599295590271,0.1264760744412251,0.7112202870642775
3,ID93403,93403,0,6822.1806640625,125.20647530999999,37.38711078,0.0,0.7000000000000001,14,0.20172901499999998,1,NaN,NaN,0,NaN,8859.761904761905,8862.0,5911.0,13436.0,186055.0,2513.0181237858574,8612.42857142857,8768.0,4769.0,13120.0,180861.0,2576.5780130131625,0.14631090190617968,0.8999755077363241,0.13599287731504925,0.8003001282597608
4,ID93389,93389,0,7436.81982421875,125.20647530999999,37.38711078,0.0,0.65,13,0.20172901499999998,1,NaN,NaN,1,NaN,8319.666666666666,7661.0,5765.0,13757.0,174713.0,2432.1204808424545,8147.666666666667,7661.0,4042.0,13017.0,171101.0,2499.20734100501,0.1543364091874245,0.9147171772435275,0.15894212435355995,0.8942073301172508
5,ID93343,93343,0,6106.2744140625,125.20647530999999,37.52159679,0.0,0.35000000000000003,7,0.20172901499999998,1,NaN,NaN,1,NaN,8401.190476190477,7816.0,5855.0,12697.0,176425.0,2045.6985755249382,8366.47619047619,7986.0,4955.0,12138.0,175696.0,2090.487350333592,0.12997516520502722,0.9447581864276058,0.12530332883127032,0.8912879526292585
6,ID93359,93359,0,3762.24267578125,125.20647530999999,37.52159679,0.0,0.55,11,0.20172901499999998,1,NaN,NaN,1,NaN,7711.047619047619,7467.0,5728.0,10249.0,161932.0,1393.6891861599013,7386.285714285715,6754.0,5343.0,10720.0,155112.0,1756.1179101318094,0.09068161707566164,0.9200230605284168,0.07591703386171271,0.5935576061512331
7,ID93374,93374,0,5951.31494140625,125.20647530999999,37.6560828,0.0,0.6000000000000001,12,0.20172901499999998,1,NaN,NaN,1,NaN,8295.0,7710.0,5863.0,12595.0,174195.0,2251.2081423093687,7949.380952380952,7503.0,3369.0,12731.0,166937.0,2633.9537102270892,0.12412518028787983,0.8137218004986245,0.11766995036375638,0.6354877200749762
8,ID93312,93312,1,4221.36083984375,128.29965353999998,33.89047452,0.0,0.4,8,0.20172901499999998,1,NaN,NaN,0,NaN,8978.142857142857,8552.0,7397.0,11666.0,188541.0,1367.4465724741967,8786.904761904761,8938.0,5293.0,12421.0,184525.0,1638.9767510481015,0.09177136851431222,1.1037777806018254,0.07862206433152756,0.7815706901620322
9,ID93568,93568,1,3055.881591796875,128.97208358999998,33.08355846,0.0,1.35,27,0.20172901499999998,1,NaN,NaN,0,NaN,7258.380952380952,6983.0,5843.0,9304.0,152426.0,1006.7515818805788,7131.285714285715,7202.0,4559.0,9857.0,149757.0,1472.0288768518485,0.07658120171241856,1.0257058155816667,0.06840600027288561,0.620353707585913

In [36]:
# Splits tables into seperate dfs by TRACK_ID

D14_pos14_ROI1_singletracks = [j for i,j in split_table_by_track(D14_allROIs_spots_filtered[0])]
D14_pos14_ROI2_singletracks = [j for i,j in split_table_by_track(D14_allROIs_spots_filtered[1])]
D14_pos14_ROI3_singletracks = [j for i,j in split_table_by_track(D14_allROIs_spots_filtered[2])]
D14_pos19_ROI1_singletracks = [j for i,j in split_table_by_track(D14_allROIs_spots_filtered[3])]
D14_pos19_ROI2_singletracks = [j for i,j in split_table_by_track(D14_allROIs_spots_filtered[4])]
D14_pos19_ROI3_singletracks = [j for i,j in split_table_by_track(D14_allROIs_spots_filtered[5])]

D14_allROIs_singletracks = [D14_pos14_ROI1_singletracks, 
                            D14_pos14_ROI2_singletracks,
                            D14_pos14_ROI3_singletracks, 
                            D14_pos19_ROI1_singletracks,
                            D14_pos19_ROI2_singletracks,
                            D14_pos19_ROI3_singletracks]

D14_allROIs_singletracks[5][5].head(10)

,LABEL,ID,TRACK_ID,QUALITY,POSITION_X,POSITION_Y,POSITION_Z,POSITION_T,FRAME,RADIUS,VISIBILITY,MANUAL_INTEGER_SPOT_FEATURE,MANUAL_DOUBLE_SPOT_FEATURE,HAS_MAX_QUALITY_IN_FRAME,MANUAL_SPOT_COLOR,MEAN_INTENSITY_CH1,MEDIAN_INTENSITY_CH1,MIN_INTENSITY_CH1,MAX_INTENSITY_CH1,TOTAL_INTENSITY_CH1,STD_INTENSITY_CH1,MEAN_INTENSITY_CH2,MEDIAN_INTENSITY_CH2,MIN_INTENSITY_CH2,MAX_INTENSITY_CH2,TOTAL_INTENSITY_CH2,STD_INTENSITY_CH2,CONTRAST_CH1,SNR_CH1,CONTRAST_CH2,SNR_CH2
65,ID122465,122465,11,8188.6943359375,116.73385667999999,52.987487939999994,0.0,1.3,26,0.20172901499999998,1,NaN,NaN,0,NaN,10234.285714285714,9188.0,7381.0,15945.0,214920.0,2422.9699779992557,10087.904761904761,9380.0,6120.0,14005.0,211846.0,2330.8914583215133,0.14505143660880004,1.0701299977657641,0.14016534997103783,1.0640982917470097
66,ID121987,121987,11,10623.826171875,116.59937066999998,52.718515919999994,0.0,0.8,16,0.20172901499999998,1,NaN,NaN,1,NaN,11127.42857142857,9819.0,7111.0,18559.0,233676.0,3446.309962429795,10677.142857142857,10171.0,5565.0,17997.0,224220.0,3193.869303614572,0.17642527837246968,0.9684271108472552,0.14954771357436047,0.869802565540722
67,ID121572,121572,11,2063.81884765625,117.13731470999998,52.718515919999994,0.0,0.4,8,0.20172901499999998,1,NaN,NaN,0,NaN,8227.904761904761,8073.0,7405.0,9763.0,172786.0,686.4948583028066,8513.52380952381,8732.0,5341.0,10726.0,178784.0,1523.6430559369087,0.03771791664852409,0.8712651528050075,0.058078967984772474,0.6134185751309286
68,ID122054,122054,11,11490.6474609375,116.59937066999998,52.85300193,0.0,1.05,21,0.20172901499999998,1,NaN,NaN,1,NaN,13494.333333333334,13434.0,7279.0,21340.0,283381.0,4281.212542415213,12779.904761904761,11786.0,6901.0,22507.0,268378.0,4272.906737863136,0.16315180271885468,0.8842399227120409,0.1434944309194881,0.7506460292635602
69,ID121641,121641,11,9966.2236328125,117.0028287,52.85300193,0.0,0.5,10,0.20172901499999998,1,NaN,NaN,0,NaN,12399.904761904761,11766.0,7825.0,18941.0,260398.0,3360.7697020885244,11953.142857142857,11248.0,5763.0,18724.0,251016.0,3531.879447060931,0.15973217730365769,1.016352351770344,0.1396679623320615,0.8295158552022506
70,ID122408,122408,11,7829.861328125,116.73385667999999,52.718515919999994,0.0,1.1,22,0.20172901499999998,1,NaN,NaN,0,NaN,13281.333333333334,13985.0,8355.0,17694.0,278908.0,2987.9569162444986,12646.47619047619,13071.0,8246.0,17666.0,265576.0,2884.520126798349,0.12998049229111255,1.0225971378183578,0.12791899569612875,0.9944502997612249
71,ID122344,122344,11,7367.13037109375,116.86834268999999,52.85300193,0.0,1.1500000000000001,23,0.20172901499999998,1,NaN,NaN,0,NaN,13197.047619047618,13003.0,7757.0,17867.0,277138.0,3240.383009401674,12617.47619047619,12330.0,6328.0,18588.0,264967.0,3444.024108786807,0.11561102878463472,0.8441058302491345,0.1062531965305249,0.7037586927972173
72,ID121099,121099,11,4636.6728515625,117.13731470999998,52.31505789,0.0,0.05,1,0.20172901499999998,1,NaN,NaN,0,NaN,11996.952380952382,11864.0,8414.0,15458.0,251936.0,2077.878544963359,12005.809523809523,12705.0,6127.0,14605.0,252122.0,2230.0439596350475,0.05401086074318281,0.5917207300225009,0.0569280703942383,0.5799479952947548
73,ID121295,121295,11,5638.013671875,117.40628672999999,52.58402991,0.0,0.15000000000000002,3,0.20172901499999998,1,NaN,NaN,0,NaN,9380.095238095239,9095.0,6917.0,13598.0,196982.0,2004.3032181973342,9154.190476190477,9105.0,4169.0,13799.0,192238.0,2378.2095706444297,0.0961264110613157,0.8208350742619038,0.10544425747677026,0.7343209232590172
74,ID122287,122287,11,5695.685546875,116.59937066999998,53.12197395,0.0,1.0,20,0.20172901499999998,1,NaN,NaN,0,NaN,11371.57142857143,10747.0,7801.0,15383.0,238803.0,2508.512359376142,10904.047619047618,11234.0,6272.0,17346.0,228985.0,2731.0988718131475,0.08951237747844704,0.7448780179621733,0.06958166224578978,0.5194708273356328

In [40]:
# Sorts the seperated dfs by FRAME and extracts the first 10

D14_pos14_ROI1_tracks10 = []
D14_pos14_ROI2_tracks10 = []
D14_pos14_ROI3_tracks10 = []
D14_pos19_ROI1_tracks10 = []
D14_pos19_ROI2_tracks10 = []
D14_pos19_ROI3_tracks10 = []

D14_allROIs_tracks10 = [D14_pos14_ROI1_tracks10, 
                        D14_pos14_ROI2_tracks10, 
                        D14_pos14_ROI3_tracks10, 
                        D14_pos19_ROI1_tracks10,
                        D14_pos19_ROI2_tracks10,
                        D14_pos19_ROI3_tracks10]

for i in D14_allROIs_singletracks:
    index = D14_allROIs_singletracks.index(i)
    for j in i:
        j = first_10_frames(j)
        D14_allROIs_tracks10[index].append(j)

D14_allROIs_tracks10[0][2].head(11)

,LABEL,ID,TRACK_ID,QUALITY,POSITION_X,POSITION_Y,POSITION_Z,POSITION_T,FRAME,RADIUS,VISIBILITY,MANUAL_INTEGER_SPOT_FEATURE,MANUAL_DOUBLE_SPOT_FEATURE,HAS_MAX_QUALITY_IN_FRAME,MANUAL_SPOT_COLOR,MEAN_INTENSITY_CH1,MEDIAN_INTENSITY_CH1,MIN_INTENSITY_CH1,MAX_INTENSITY_CH1,TOTAL_INTENSITY_CH1,STD_INTENSITY_CH1,MEAN_INTENSITY_CH2,MEDIAN_INTENSITY_CH2,MIN_INTENSITY_CH2,MAX_INTENSITY_CH2,TOTAL_INTENSITY_CH2,STD_INTENSITY_CH2,CONTRAST_CH1,SNR_CH1,CONTRAST_CH2,SNR_CH2
106,ID145511,145511,2,2323.64111328125,67.91543505,112.69927637999999,0.0,0.25,5,0.20172901499999998,1,NaN,NaN,0,NaN,9428.238095238095,9410.0,8257.0,11017.0,197993.0,781.0314913473019,9718.904761904761,9941.0,7233.0,12672.0,204097.0,1478.0291575189544,0.04237701951235565,0.9815164261467096,0.056855356007813856,0.7074897480004992
104,ID145442,145442,2,4079.02685546875,67.91543505,112.56479037,0.0,0.30000000000000004,6,0.20172901499999998,1,NaN,NaN,0,NaN,9692.857142857143,9531.0,8231.0,12802.0,203550.0,1268.5735408605321,9791.095238095239,9610.0,7558.0,12924.0,205613.0,1698.6788662004926,0.06589166314838632,0.9446774810784179,0.0897813618623165,0.9497226589580692
88,ID145538,145538,2,3399.129638671875,67.91543505,112.56479037,0.0,0.35000000000000003,7,0.20172901499999998,1,NaN,NaN,0,NaN,9859.857142857143,9683.0,8233.0,12326.0,207057.0,1292.8113661982666,9784.238095238095,9324.0,6681.0,13288.0,205469.0,1832.3379029197074,0.059097483034169514,0.8511351088232864,0.06594209712301369,0.6606639102321572
97,ID145553,145553,2,2189.7705078125,67.91543505,112.56479037,0.0,0.4,8,0.20172901499999998,1,NaN,NaN,0,NaN,9391.619047619048,9287.0,8363.0,10877.0,197224.0,720.2407567050393,9427.285714285714,9110.0,6965.0,12317.0,197973.0,1461.1419213360878,0.04323723882570751,1.0808555100902193,0.030658461922908747,0.38384850551977034
89,ID145478,145478,2,2445.07373046875,67.91543505,112.56479037,0.0,0.5,10,0.20172901499999998,1,NaN,NaN,0,NaN,9195.095238095239,8954.0,7982.0,11004.0,193097.0,834.413261205855,9441.666666666666,9269.0,6109.0,13497.0,198275.0,1524.793865849851,0.04189145896072282,0.8861516241941044,0.05997952479344364,0.7007660730116214
100,ID145498,145498,2,1912.829345703125,67.91543505,112.56479037,0.0,0.55,11,0.20172901499999998,1,NaN,NaN,0,NaN,9224.42857142857,9039.0,8397.0,10473.0,193713.0,567.5208869661601,9362.0,9546.0,6876.0,11500.0,196602.0,1288.557100015362,0.03941615239275695,1.2327425455600143,0.05071056518541228,0.7013104591312229
114,ID145458,145458,2,3059.701904296875,67.91543505,112.69927637999999,0.0,0.6000000000000001,12,0.20172901499999998,1,NaN,NaN,0,NaN,9430.619047619048,9473.0,7579.0,11433.0,198043.0,1085.2976308916589,9474.42857142857,9809.0,5856.0,11725.0,198963.0,1712.9525846160652,0.06228150516207677,1.0189217241954203,0.06532699640385269,0.6783400172017737
108,ID145573,145573,2,2510.63134765625,67.91543505,112.69927637999999,0.0,0.65,13,0.20172901499999998,1,NaN,NaN,0,NaN,8978.42857142857,8900.0,7694.0,10666.0,188547.0,843.5631316877576,9264.952380952382,9271.0,6997.0,13112.0,194564.0,1586.563155887293,0.05011957100638057,1.0159710424648372,0.0607466126563508,0.6688461551177302
96,ID145612,145612,2,2601.04150390625,67.91543505,112.69927637999999,0.0,0.7000000000000001,14,0.20172901499999998,1,NaN,NaN,0,NaN,9154.761904761905,9149.0,7910.0,10958.0,192250.0,949.4718481746526,9235.047619047618,9290.0,6729.0,12276.0,193936.0,1496.8633029168186,0.04898944394692854,0.9005884007800976,0.05639482985545356,0.6587187372691558
115,ID145587,145587,2,2166.2236328125,67.91543505,112.56479037,0.0,0.75,15,0.20172901499999998,1,NaN,NaN,0,NaN,8601.285714285714,8435.0,7590.0,10225.0,180627.0,776.5539995941778,8977.714285714286,8989.0,5636.0,11889.0,188532.0,1557.471127914002,0.04049234544539418,0.8620962432286011,0.06488180970939597,0.7024207257474167

In [44]:
# Concatenates all filtered seperate track dfs into one df per ROI

D14_allROIs_alltracks10 = []

for i in D14_allROIs_tracks10:
    for df in i:
        df = pd.concat(i)
    D14_allROIs_alltracks10.append(df)
D14_allROIs_alltracks10[4].head()

,LABEL,ID,TRACK_ID,QUALITY,POSITION_X,POSITION_Y,POSITION_Z,POSITION_T,FRAME,RADIUS,VISIBILITY,MANUAL_INTEGER_SPOT_FEATURE,MANUAL_DOUBLE_SPOT_FEATURE,HAS_MAX_QUALITY_IN_FRAME,MANUAL_SPOT_COLOR,MEAN_INTENSITY_CH1,MEDIAN_INTENSITY_CH1,MIN_INTENSITY_CH1,MAX_INTENSITY_CH1,TOTAL_INTENSITY_CH1,STD_INTENSITY_CH1,MEAN_INTENSITY_CH2,MEDIAN_INTENSITY_CH2,MIN_INTENSITY_CH2,MAX_INTENSITY_CH2,TOTAL_INTENSITY_CH2,STD_INTENSITY_CH2,CONTRAST_CH1,SNR_CH1,CONTRAST_CH2,SNR_CH2
5,ID93343,93343,0,6106.2744140625,125.20647530999999,37.52159679,0.0,0.35000000000000003,7,0.20172901499999998,1,NaN,NaN,1,NaN,8401.190476190477,7816.0,5855.0,12697.0,176425.0,2045.6985755249382,8366.47619047619,7986.0,4955.0,12138.0,175696.0,2090.487350333592,0.12997516520502722,0.9447581864276058,0.12530332883127032,0.8912879526292585
1,ID93315,93315,0,6076.1396484375,125.20647530999999,37.6560828,0.0,0.4,8,0.20172901499999998,1,NaN,NaN,1,NaN,8216.190476190477,7783.0,5471.0,12593.0,172540.0,2175.239449326157,8262.57142857143,7325.0,5435.0,12763.0,173514.0,2154.32018445329,0.1248002516360828,0.8381726393574688,0.11321921351153034,0.7801433526721028
0,ID93328,93328,0,6514.07470703125,125.20647530999999,37.790568809999996,0.0,0.45,9,0.20172901499999998,1,NaN,NaN,1,NaN,8314.47619047619,7377.0,6302.0,13218.0,174604.0,1945.301869095067,8154.428571428572,7852.0,4935.0,14106.0,171243.0,2120.399622038935,0.12736385464377237,0.9657394524473941,0.10806233226728526,0.7500944555303242
2,ID93304,93304,0,6424.98095703125,125.07198929999998,37.790568809999996,0.0,0.5,10,0.20172901499999998,1,NaN,NaN,1,NaN,8266.47619047619,7857.0,5724.0,12898.0,173596.0,2427.7421324977577,7991.0,7966.0,4135.0,12747.0,167811.0,2522.9776059251894,0.13772266715602108,0.8243599295590271,0.1264760744412251,0.7112202870642775
6,ID93359,93359,0,3762.24267578125,125.20647530999999,37.52159679,0.0,0.55,11,0.20172901499999998,1,NaN,NaN,1,NaN,7711.047619047619,7467.0,5728.0,10249.0,161932.0,1393.6891861599013,7386.285714285715,6754.0,5343.0,10720.0,155112.0,1756.1179101318094,0.09068161707566164,0.9200230605284168,0.07591703386171271,0.5935576061512331

In [50]:
# Extracts the columns "TRACK_ID" and "MEAN_INTENSITY_CH2" and calculates the mean of each track

D14_allROIs_meanint = []

for df in D14_allROIs_alltracks10:
    df = meanint_tracks_ch2(df)
    D14_allROIs_meanint.append(df)
    
D14_allROIs_meanint[5].head()

  TRACK_ID  MEAN_INTENSITY_CH2
0        0            10212.69
1        1            10545.21
2        3            10443.82
3        4            10217.10
4        8            15150.17